// Généré par scripts/prepare-artworks.mjs — NE PAS ÉDITER À LA MAIN.
// Source : Metropolitan Museum of Art, Open Access (domaine public / CC0).
import type { Artwork } from '@mimic/shared';

export const ARTWORKS_SEED: Artwork[] = [
  {
    id: 'madame-roulin-and-her-baby',
    title: 'Madame Roulin and Her Baby',
    author: 'Vincent van Gogh',
    year: '1888',
    width: 1028,
    height: 1280,
    difficulty: 2,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/madame-roulin-and-her-baby.jpg',
  },
  {
    id: 'trees-and-houses-near-the-jas-de-bouffan',
    title: 'Trees and Houses Near the Jas de Bouffan',
    author: 'Paul Cézanne',
    year: '1885–86',
    width: 1280,
    height: 962,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/trees-and-houses-near-the-jas-de-bouffan.jpg',
  },
  {
    id: 'young-girl-bathing',
    title: 'Young Girl Bathing',
    author: 'Auguste Renoir',
    year: '1892',
    width: 1024,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/young-girl-bathing.jpg',
  },
  {
    id: 'the-dance-class',
    title: 'The Dance Class',
    author: 'Edgar Degas',
    year: '1874',
    width: 1187,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-dance-class.jpg',
  },
  {
    id: 'portrait-of-gerard-de-lairesse',
    title: 'Portrait of Gerard de Lairesse',
    author: 'Rembrandt (Rembrandt van Rijn)',
    year: '1665–67',
    width: 997,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/portrait-of-gerard-de-lairesse.jpg',
  },
  {
    id: 'young-woman-with-a-water-pitcher',
    title: 'Young Woman with a Water Pitcher',
    author: 'Johannes Vermeer',
    year: 'ca. 1662',
    width: 1138,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/young-woman-with-a-water-pitcher.jpg',
  },
  {
    id: 'circus-sideshow-parade-de-cirque',
    title: 'Circus Sideshow (Parade de cirque)',
    author: 'Georges Seurat',
    year: '1887–88',
    width: 1280,
    height: 856,
    difficulty: 2,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/circus-sideshow-parade-de-cirque.jpg',
  },
  {
    id: 'ia-orana-maria-hail-mary',
    title: 'Ia Orana Maria (Hail Mary)',
    author: 'Paul Gauguin',
    year: '1891',
    width: 1007,
    height: 1280,
    difficulty: 2,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/ia-orana-maria-hail-mary.jpg',
  },
  {
    id: 'the-harvest-pontoise-la-recolte-pontoise',
    title: 'The Harvest, Pontoise (La Récolte, Pontoise)',
    author: 'Camille Pissarro',
    year: '1881',
    width: 1280,
    height: 1064,
    difficulty: 2,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-harvest-pontoise-la-recolte-pontoise.jpg',
  },
  {
    id: 'the-spanish-singer',
    title: 'The Spanish Singer',
    author: 'Edouard Manet',
    year: '1860',
    width: 1006,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-spanish-singer.jpg',
  },
  {
    id: 'madame-x-virginie-amelie-avegno-gautreau',
    title: 'Madame X (Virginie Amélie Avegno Gautreau)',
    author: 'John Singer Sargent',
    year: '1883–84',
    width: 748,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/madame-x-virginie-amelie-avegno-gautreau.jpg',
  },
  {
    id: 'the-gulf-stream',
    title: 'The Gulf Stream',
    author: 'Winslow Homer',
    year: '1899; reworked by 1906',
    width: 1280,
    height: 790,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-gulf-stream.jpg',
  },
  {
    id: 'after-the-hunt',
    title: 'After the Hunt',
    author: 'Gustave Courbet',
    year: 'ca. 1859',
    width: 1010,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/after-the-hunt.jpg',
  },
  {
    id: 'venice-from-the-porch-of-madonna-della-salute',
    title: 'Venice, from the Porch of Madonna della Salute',
    author: 'Joseph Mallord William Turner',
    year: 'ca. 1835',
    width: 1280,
    height: 955,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/venice-from-the-porch-of-madonna-della-salute.jpg',
  },
  {
    id: 'the-abduction-of-rebecca',
    title: 'The Abduction of Rebecca',
    author: 'Eugène Delacroix',
    year: '1846',
    width: 1044,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-abduction-of-rebecca.jpg',
  },
];
