// Généré par scripts/prepare-artworks.mjs — NE PAS ÉDITER À LA MAIN.
// Source : Metropolitan Museum of Art, Open Access (domaine public / CC0).
import type { Artwork } from '@mimic/shared';

export const ARTWORKS_SEED: Artwork[] = [
  {
    id: 'madame-roulin-and-her-baby',
    title: 'Madame Roulin and Her Baby',
    author: 'Vincent van Gogh',
    year: '1888',
    width: 1028,
    height: 1280,
    difficulty: 2,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/madame-roulin-and-her-baby.jpg',
  },
  {
    id: 'trees-and-houses-near-the-jas-de-bouffan',
    title: 'Trees and Houses Near the Jas de Bouffan',
    author: 'Paul Cézanne',
    year: '1885–86',
    width: 1280,
    height: 962,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/trees-and-houses-near-the-jas-de-bouffan.jpg',
  },
  {
    id: 'young-girl-bathing',
    title: 'Young Girl Bathing',
    author: 'Auguste Renoir',
    year: '1892',
    width: 1024,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/young-girl-bathing.jpg',
  },
  {
    id: 'the-dance-class',
    title: 'The Dance Class',
    author: 'Edgar Degas',
    year: '1874',
    width: 1187,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-dance-class.jpg',
  },
  {
    id: 'portrait-of-gerard-de-lairesse',
    title: 'Portrait of Gerard de Lairesse',
    author: 'Rembrandt (Rembrandt van Rijn)',
    year: '1665–67',
    width: 997,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/portrait-of-gerard-de-lairesse.jpg',
  },
  {
    id: 'young-woman-with-a-water-pitcher',
    title: 'Young Woman with a Water Pitcher',
    author: 'Johannes Vermeer',
    year: 'ca. 1662',
    width: 1138,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/young-woman-with-a-water-pitcher.jpg',
  },
  {
    id: 'circus-sideshow-parade-de-cirque',
    title: 'Circus Sideshow (Parade de cirque)',
    author: 'Georges Seurat',
    year: '1887–88',
    width: 1280,
    height: 856,
    difficulty: 2,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/circus-sideshow-parade-de-cirque.jpg',
  },
  {
    id: 'ia-orana-maria-hail-mary',
    title: 'Ia Orana Maria (Hail Mary)',
    author: 'Paul Gauguin',
    year: '1891',
    width: 1007,
    height: 1280,
    difficulty: 2,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/ia-orana-maria-hail-mary.jpg',
  },
  {
    id: 'the-harvest-pontoise-la-recolte-pontoise',
    title: 'The Harvest, Pontoise (La Récolte, Pontoise)',
    author: 'Camille Pissarro',
    year: '1881',
    width: 1280,
    height: 1064,
    difficulty: 2,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-harvest-pontoise-la-recolte-pontoise.jpg',
  },
  {
    id: 'the-spanish-singer',
    title: 'The Spanish Singer',
    author: 'Edouard Manet',
    year: '1860',
    width: 1006,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-spanish-singer.jpg',
  },
  {
    id: 'madame-x-virginie-amelie-avegno-gautreau',
    title: 'Madame X (Virginie Amélie Avegno Gautreau)',
    author: 'John Singer Sargent',
    year: '1883–84',
    width: 748,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/madame-x-virginie-amelie-avegno-gautreau.jpg',
  },
  {
    id: 'the-gulf-stream',
    title: 'The Gulf Stream',
    author: 'Winslow Homer',
    year: '1899; reworked by 1906',
    width: 1280,
    height: 790,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-gulf-stream.jpg',
  },
  {
    id: 'after-the-hunt',
    title: 'After the Hunt',
    author: 'Gustave Courbet',
    year: 'ca. 1859',
    width: 1010,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/after-the-hunt.jpg',
  },
  {
    id: 'venice-from-the-porch-of-madonna-della-salute',
    title: 'Venice, from the Porch of Madonna della Salute',
    author: 'Joseph Mallord William Turner',
    year: 'ca. 1835',
    width: 1280,
    height: 955,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/venice-from-the-porch-of-madonna-della-salute.jpg',
  },
  {
    id: 'the-abduction-of-rebecca',
    title: 'The Abduction of Rebecca',
    author: 'Eugène Delacroix',
    year: '1846',
    width: 1044,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-abduction-of-rebecca.jpg',
  },
  {
    id: 'diana-and-actaeon-diana-surprised-in-her-bath',
    title: 'Diana and Actaeon (Diana Surprised in Her Bath)',
    author: 'Camille Corot',
    year: '1836',
    width: 934,
    height: 1280,
    difficulty: 2,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/diana-and-actaeon-diana-surprised-in-her-bath.jpg',
  },
  {
    id: 'haystacks-autumn',
    title: 'Haystacks: Autumn',
    author: 'Jean-François Millet',
    year: 'ca. 1874',
    width: 1280,
    height: 1000,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/haystacks-autumn.jpg',
  },
  {
    id: 'view-of-marly-le-roi-from-coeur-volant',
    title: 'View of Marly-le-Roi from Coeur-Volant',
    author: 'Alfred Sisley',
    year: '1876',
    width: 1280,
    height: 909,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/view-of-marly-le-roi-from-coeur-volant.jpg',
  },
  {
    id: 'the-pink-dress-albertie-marguerite-carre-later-m',
    title:
      'The Pink Dress (Albertie-Marguerite Carré, later Madame Ferdinand-Henri Himmes, 1854–1935)',
    author: 'Berthe Morisot',
    year: 'ca. 1870',
    width: 1280,
    height: 1041,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-pink-dress-albertie-marguerite-carre-later-m.jpg',
  },
  {
    id: 'the-englishman-william-tom-warrener-1861-1934-at',
    title: 'The Englishman (William Tom Warrener, 1861–1934) at the Moulin Rouge',
    author: 'Henri de Toulouse-Lautrec',
    year: '1892',
    width: 962,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-englishman-william-tom-warrener-1861-1934-at.jpg',
  },
  {
    id: 'the-repast-of-the-lion',
    title: 'The Repast of the Lion',
    author: 'Henri Rousseau (le Douanier)',
    year: 'ca. 1907',
    width: 1280,
    height: 901,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-repast-of-the-lion.jpg',
  },
  {
    id: 'the-yellow-room',
    title: 'The Yellow Room',
    author: 'James McNeill Whistler',
    year: 'ca. 1883–84',
    width: 914,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-yellow-room.jpg',
  },
  {
    id: 'the-adoration-of-the-shepherds',
    title: 'The Adoration of the Shepherds',
    author: 'El Greco (Domenikos Theotokopoulos)',
    year: 'ca. 1605–10',
    width: 835,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/the-adoration-of-the-shepherds.jpg',
  },
  {
    id: 'tiburcio-perez-y-cuervo-1785-86-1841-the-archite',
    title: 'Tiburcio Pérez y Cuervo (1785/86–1841), the Architect',
    author: 'Goya (Francisco de Goya y Lucientes)',
    year: '1820',
    width: 1017,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/tiburcio-perez-y-cuervo-1785-86-1841-the-archite.jpg',
  },
  {
    id: 'portrait-of-a-man-possibly-a-self-portrait',
    title: 'Portrait of a Man, Possibly a Self-Portrait',
    author: 'Velázquez (Diego Rodríguez de Silva y Velázquez)',
    year: 'ca. 1635',
    width: 1020,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/portrait-of-a-man-possibly-a-self-portrait.jpg',
  },
  {
    id: 'venus-and-the-lute-player',
    title: 'Venus and the Lute Player',
    author: 'Titian',
    year: 'ca. 1565–70',
    width: 1280,
    height: 1037,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/venus-and-the-lute-player.jpg',
  },
  {
    id: 'blind-orion-searching-for-the-rising-sun',
    title: 'Blind Orion Searching for the Rising Sun',
    author: 'Nicolas Poussin',
    year: '1658',
    width: 1280,
    height: 836,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/blind-orion-searching-for-the-rising-sun.jpg',
  },
  {
    id: 'marie-emilie-coignet-de-courson-1716-1806-with-a',
    title: 'Marie Emilie Coignet de Courson (1716–1806) with a Dog',
    author: 'Jean Honoré Fragonard',
    year: 'ca. 1769',
    width: 1024,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/marie-emilie-coignet-de-courson-1716-1806-with-a.jpg',
  },
  {
    id: 'antoine-laurent-lavoisier-1743-1794-and-marie-an',
    title:
      'Antoine Laurent Lavoisier (1743–1794) and Marie Anne Lavoisier (Marie Anne Pierrette Paulze, 1758–1836)',
    author: 'Jacques Louis David',
    year: '1788',
    width: 972,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/antoine-laurent-lavoisier-1743-1794-and-marie-an.jpg',
  },
  {
    id: 'portrait-of-a-man-possibly-an-architect-or-geogr',
    title: 'Portrait of a Man, Possibly an Architect or Geographer',
    author: 'Peter Paul Rubens',
    year: '1597',
    width: 855,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/portrait-of-a-man-possibly-an-architect-or-geogr.jpg',
  },
  {
    id: 'lucas-van-uffel-died-1637',
    title: 'Lucas van Uffel (died 1637)',
    author: 'Anthony van Dyck',
    year: 'ca. 1622',
    width: 1061,
    height: 1280,
    difficulty: 4,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/lucas-van-uffel-died-1637.jpg',
  },
  {
    id: 'young-man-and-woman-in-an-inn',
    title: 'Young Man and Woman in an Inn',
    author: 'Frans Hals',
    year: '1623',
    width: 969,
    height: 1280,
    difficulty: 3,
    recommendedMaxPlayers: 8,
    maxZoom: 8,
    imageUrl: '/artworks/young-man-and-woman-in-an-inn.jpg',
  },
];
